version: "3.8"
services:
    db:
      container_name: db
      build: ./db
      environment:
        MYSQL_PASSWORd: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE : fullcycledb
      restart: always
      # volumes:
      #   - ./mysql:/var/lib/mysql

    app:
      container_name: app
      entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
      command: node index.js
      build:
        context: ./app
      depends_on:
        - db
      #restart: always

    nginx:
      container_name: nginx
      #entrypoint: dockerize -wait http://app:3000 -timeout 60s docker-entrypoint.sh
      build:
        context: ./nginx
      ports:
        - "8080:80"
      #depends_on:
      #  - app
      restart: always
      # networks:
      #   - node-network



# networks:
#   node-network:
#     driver: bridge
